pipeline {
    agent any
    stages {
        stage('Run cond-env') {
            steps {
                sh """
                conda remove -n run-py-env --all -y
                conda env create -f JenkinsFile/conda_env_file/env/env.yml 
                conda run -n run-py-env python test.py
                conda remove -n run-py-env --all -y
                """
            }
        }
    }
}
